### ISSUE TITLE
Way to link account without mobile data?

### ISSUE THREAD

**Issue by Petoriaforever** [Szybet/redmi10-liberated#1]
So ive been trying to install nusantara os... and it seems like everything should work, but one problem, **my mobile data provider hates me!** thats just amazing (sarcasm.. im in pain right now) so i need another way to merge it. _- me_

**Comment by Szybet** [comment]
so you can't request the bootloader unlocking without mobile data? If so, i have seen somewhere someone trying over bluetooth network with another phone with mobile data

**Comment by Petoriaforever** [comment]
Alright thanks! I'll test it out although I don't know where I'm getting Bluetooth WiFi from someone... But I'll try asking my neighbors or smthn! Anyways thanks for the help!

**Comment by Petoriaforever** [comment]
Sorry for the opening of this issue but... I was wondering if the redmi 10 works for redmi 10/redmi 10 2022 as it shows on the website https://wiki.pixelexperience.org/devices/fog/
But lists the code name is "fog" even tho both redmi 10/10 2022 is the code name "Selene" and says the specs are different?
For example it doesn't mention the mediatek processor instead it says it's a Qualcomm Snapdragon...

**Comment by Petoriaforever** [comment]
Sorry for the opening of this issue but... I was wondering if the redmi 10 works for redmi 10/redmi 10 2022 as it shows on the website https://wiki.pixelexperience.org/devices/fog/
But lists the code name is "fog" even tho both redmi 10/10 2022 is the code name "Selene" and says the specs are different?
For example it doesn't mention the mediatek processor instead it says it's a Qualcomm Snapdragon...

**Comment by Szybet** [comment]
Its propably a diffrent phone, with similar specs, IDK
