### ISSUE TITLE
More information about twrp?

### ISSUE THREAD

**Issue by ghost** [Szybet/redmi10-liberated#3]
So my friend recommended me to this GitHub page (petoria forever), I'm a beginner to custom roms. So can you help me with twrp? Explaining it further would be nice! (If you're still active lol)

**Comment by Szybet** [comment]
I'm active
But i don't see a reason that I would explain it. Google? XDA? there are many resources and I'm not an android developer to feel confident to explain it.

**Comment by ghost** [comment]
Yeah, I tried searching it up. But none of them actually gave me a tutorial on a beginners level, oh all those big words... I just want to know how to do it! Not become a computer engineer, so if you could send me an actual begginers tutorial or type it yourself! It would be helpful!

**Comment by Szybet** [comment]
it is in the guide, how to flash it?
